import path

data = {
    0:{
        'PATH' : path.get_resource_path('pic/other/peabullet.png'),
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.008,
        'SUMMON_CD' : -1,
        'SIZE' : (28,28),
        'SPEED' : (4,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 1,
        'ATT' : 1,
    },

    1:{
        'PATH' : path.get_resource_path('pic/zombie/0/%d.png'),
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (77,96),
        'SPEED' : (-8,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 5,
        'ATT' : 1,
    },

    2:{
        'PATH' : path.get_resource_path('pic/other/sunlight/%d.png'),
        'IMAGE_INDEX_MAX' : 30,
        'IMAGE_INDEX_CD' : 0.06,
        'POSITION_CD' : 0.05,
        'SUMMON_CD' : -1,
        'SIZE' : (80,80),
        'SPEED' : (0,2.5),
        'CAN_LOOT' : True,
        'PRICE' : 25,
        'HP' : 100000,
        'ATT' : 0,
    },

    3:{
        'PATH' : path.get_resource_path('pic/plant/sunflower/%d.png'),
        'IMAGE_INDEX_MAX' : 19,
        'IMAGE_INDEX_CD' : 0.07,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : 7,
        'SIZE' : (96,96),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 50,
        'HP' : 5,
        'ATT' : 0,
    },

    4:{
        'PATH' : path.get_resource_path('pic/plant/peashooter/%d.png'),
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.15,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : 1.9,
        'SIZE' : (96,96),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 100,
        'HP' : 5,
        'ATT' : 0,
    },

    5:{
        'PATH' :path.get_resource_path( 'pic/plant/nut/0.png'),
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.15,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : -1,
        'SIZE' : (96,96),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 75,
        'HP' : 10000,
        'ATT' : 0,

    },

    6:{
        'PATH' : path.get_resource_path('pic/zombie/1/%d.png'),
        'IMAGE_INDEX_MAX' : 10,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (110,96),
        'SPEED' : (-8,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 5,
        'ATT' : 1,
    },

    7:{
        'PATH' : path.get_resource_path('pic/zombie/0/%d.png'),
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (77,96),
        'SPEED' : (-8,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 5,
        'ATT' : 1,
    },

    8:{
        'PATH' : path.get_resource_path('pic/plant/potato/%d.png'),
        'IMAGE_INDEX_MAX' : 3,
        'IMAGE_INDEX_CD' : 5,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : -1,
        'SIZE' : (96,96),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 50,
        'HP' : 1,
        'ATT' : 100,
    },

    9:{
        'PATH' : path.get_resource_path('pic/plant/jalapeno/%d.png'),
        'IMAGE_INDEX_MAX' : 13,
        'IMAGE_INDEX_CD' : 0.1,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : 1.2,
        'SIZE' : (76,76),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 125,
        'HP' : 1,
        'ATT' : 0,
    },

    10:{
        'PATH' : path.get_resource_path('pic/other/fire.png'),
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 10000,
        'SUMMON_CD' : -1,
        'SIZE' : (680,64),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 1,
        'ATT' : 5,
    },

    11:{
        'PATH' :path.get_resource_path( 'pic/zombie/2/%d.png'),
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (77,96),
        'SPEED' : (-8,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 10,
        'ATT' : 1,
    },

    12:{
        'PATH' : path.get_resource_path('pic/zombie/3/%d.png'),
        'IMAGE_INDEX_MAX' : 15,
        'IMAGE_INDEX_CD' : 0.15,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (77,96),
        'SPEED' : (-13,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 5,
        'ATT' : 1,
    },

    13:{
        'PATH' : path.get_resource_path('pic/plant/coconut/0.png'),
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.15,
        'POSITION_CD' : 100000,
        'SUMMON_CD' : 2.8,
        'SIZE' : (96,96),
        'SPEED' : (0,0),
        'CAN_LOOT' : False,
        'PRICE' : 175,
        'HP' : 5,
        'ATT' : 0,
    },

    14:{
        'PATH' : path.get_resource_path('pic/other/cocobullet.png'),
        'IMAGE_INDEX_MAX' : 0,
        'IMAGE_INDEX_CD' : 0.2,
        'POSITION_CD' : 0.008,
        'SUMMON_CD' : -1,
        'SIZE' : (40,40),
        'SPEED' : (5,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 1,
        'ATT' : 2.5,
    },

    15:{
        'PATH' : path.get_resource_path('pic/zombie/4/%d.png'),
        'IMAGE_INDEX_MAX' : 2,
        'IMAGE_INDEX_CD' : 10,
        'POSITION_CD' : 0.2,
        'SUMMON_CD' : -1,
        'SIZE' : (77,96),
        'SPEED' : (-8,0),
        'CAN_LOOT' : False,
        'PRICE' : 0,
        'HP' : 3,
        'ATT' : 1,
    },


}